// <auto-generated />
using System;
using Fitness.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Fitness.Migrations
{
    [DbContext(typeof(ModelContext))]
    partial class ModelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("C##FITNESS")
                .UseCollation("USING_NLS_COMP")
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fitness.Models.Infofitness", b =>
                {
                    b.Property<decimal>("Idif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("IDIF");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Idif"));

                    b.Property<string>("Aboutus")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(300)")
                        .HasColumnName("ABOUTUS");

                    b.Property<string>("Email")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(500)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Facebook")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(300)")
                        .HasColumnName("FACEBOOK");

                    b.Property<decimal?>("Inprofileid")
                        .IsRequired()
                        .HasColumnType("NUMBER")
                        .HasColumnName("INPROFILEID");

                    b.Property<string>("Linkedin")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(300)")
                        .HasColumnName("LINKEDIN");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(300)")
                        .HasColumnName("LOCATION");

                    b.Property<string>("Phone")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(300)")
                        .HasColumnName("PHONE");

                    b.Property<string>("Photoaboutus")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(300)")
                        .HasColumnName("PHOTOABOUTUS");

                    b.HasKey("Idif")
                        .HasName("SYS_C008447");

                    b.HasIndex("Inprofileid");

                    b.ToTable("INFOFITNESS", "C##FITNESS");
                });

            modelBuilder.Entity("Fitness.Models.Profile", b =>
                {
                    b.Property<decimal>("Profileid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("PROFILEID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Profileid"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("DATE")
                        .HasColumnName("DATE_OF_BIRTH");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Lname")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("LNAME");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("NAME");

                    b.Property<string>("Photo")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(150)")
                        .HasColumnName("PHOTO");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("USERNAME");

                    b.Property<string>("Userpassword")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("USERPASSWORD");

                    b.HasKey("Profileid")
                        .HasName("SYS_C008427");

                    b.ToTable("PROFILE", "C##FITNESS");
                });

            modelBuilder.Entity("Fitness.Models.Role", b =>
                {
                    b.Property<decimal>("Roleid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ROLEID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Roleid"));

                    b.Property<string>("Rname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("RNAME");

                    b.Property<decimal?>("Rprofileid")
                        .HasColumnType("NUMBER")
                        .HasColumnName("RPROFILEID");

                    b.HasKey("Roleid")
                        .HasName("SYS_C008436");

                    b.HasIndex("Rprofileid");

                    b.ToTable("ROLE", "C##FITNESS");
                });

            modelBuilder.Entity("Fitness.Models.Subscription", b =>
                {
                    b.Property<decimal>("Subscrid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("SUBSCRID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Subscrid"));

                    b.Property<decimal?>("Countweeks")
                        .HasColumnType("NUMBER")
                        .HasColumnName("COUNTWEEKS");

                    b.Property<string>("Nameplan")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("NAMEPLAN");

                    b.Property<decimal?>("Price")
                        .HasColumnType("NUMBER")
                        .HasColumnName("PRICE");

                    b.Property<decimal?>("Sidwop")
                        .HasColumnType("NUMBER")
                        .HasColumnName("SIDWOP");

                    b.HasKey("Subscrid")
                        .HasName("SYS_C008441");

                    b.HasIndex("Sidwop");

                    b.ToTable("SUBSCRIPTIONS", "C##FITNESS");
                });

            modelBuilder.Entity("Fitness.Models.Testimonial", b =>
                {
                    b.Property<decimal>("Testimoid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("TESTIMOID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Testimoid"));

                    b.Property<string>("Feedback")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(1000)")
                        .HasColumnName("FEEDBACK");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("STATUS");

                    b.Property<decimal?>("Tprofileid")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TPROFILEID");

                    b.HasKey("Testimoid")
                        .HasName("SYS_C008429");

                    b.HasIndex("Tprofileid");

                    b.ToTable("TESTIMONIAL", "C##FITNESS");
                });

            modelBuilder.Entity("Fitness.Models.Typeperson", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<DateTime?>("Enddate")
                        .HasColumnType("DATE")
                        .HasColumnName("ENDDATE");

                    b.Property<DateTime?>("Startdate")
                        .HasColumnType("DATE")
                        .HasColumnName("STARTDATE");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("STATUS");

                    b.Property<decimal?>("Tprofileid")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TPROFILEID");

                    b.Property<decimal?>("Tsubscrid")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TSUBSCRID");

                    b.HasKey("Id")
                        .HasName("SYS_C008450");

                    b.HasIndex("Tprofileid");

                    b.HasIndex("Tsubscrid");

                    b.ToTable("TYPEPERSON", "C##FITNESS");
                });

            modelBuilder.Entity("Fitness.Models.Workoutplan", b =>
                {
                    b.Property<decimal>("Idwop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("IDWOP");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Idwop"));

                    b.Property<string>("Day1")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(300)")
                        .HasColumnName("DAY1");

                    b.Property<string>("Day2")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(300)")
                        .HasColumnName("DAY2");

                    b.Property<string>("Day3")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(300)")
                        .HasColumnName("DAY3");

                    b.Property<string>("Day4")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(300)")
                        .HasColumnName("DAY4");

                    b.Property<string>("Day5")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(300)")
                        .HasColumnName("DAY5");

                    b.Property<string>("Day6")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(300)")
                        .HasColumnName("DAY6");

                    b.Property<string>("Day7")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(300)")
                        .HasColumnName("DAY7");

                    b.Property<string>("Goals")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(500)")
                        .HasColumnName("GOALS");

                    b.Property<decimal?>("Numberofweek")
                        .HasColumnType("NUMBER")
                        .HasColumnName("NUMBEROFWEEK");

                    b.HasKey("Idwop")
                        .HasName("SYS_C008439");

                    b.ToTable("WORKOUTPLANS", "C##FITNESS");
                });

            modelBuilder.Entity("Fitness.Models.Infofitness", b =>
                {
                    b.HasOne("Fitness.Models.Profile", "Inprofile")
                        .WithMany("Infofitnesses")
                        .HasForeignKey("Inprofileid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_INFO");

                    b.Navigation("Inprofile");
                });

            modelBuilder.Entity("Fitness.Models.Role", b =>
                {
                    b.HasOne("Fitness.Models.Profile", "Rprofile")
                        .WithMany("Roles")
                        .HasForeignKey("Rprofileid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_ROLE");

                    b.Navigation("Rprofile");
                });

            modelBuilder.Entity("Fitness.Models.Subscription", b =>
                {
                    b.HasOne("Fitness.Models.Workoutplan", "SidwopNavigation")
                        .WithMany("Subscriptions")
                        .HasForeignKey("Sidwop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_SUBSC");

                    b.Navigation("SidwopNavigation");
                });

            modelBuilder.Entity("Fitness.Models.Testimonial", b =>
                {
                    b.HasOne("Fitness.Models.Profile", "Tprofile")
                        .WithMany("Testimonials")
                        .HasForeignKey("Tprofileid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_PROFILE");

                    b.Navigation("Tprofile");
                });

            modelBuilder.Entity("Fitness.Models.Typeperson", b =>
                {
                    b.HasOne("Fitness.Models.Profile", "Tprofile")
                        .WithMany("Typepeople")
                        .HasForeignKey("Tprofileid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FKT_PROFILE");

                    b.HasOne("Fitness.Models.Subscription", "Tsubscr")
                        .WithMany("Typepeople")
                        .HasForeignKey("Tsubscrid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FKT_SUBSCR");

                    b.Navigation("Tprofile");

                    b.Navigation("Tsubscr");
                });

            modelBuilder.Entity("Fitness.Models.Profile", b =>
                {
                    b.Navigation("Infofitnesses");

                    b.Navigation("Roles");

                    b.Navigation("Testimonials");

                    b.Navigation("Typepeople");
                });

            modelBuilder.Entity("Fitness.Models.Subscription", b =>
                {
                    b.Navigation("Typepeople");
                });

            modelBuilder.Entity("Fitness.Models.Workoutplan", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
